### PR TITLE
added tocDepth, rootHref, extension, image download and copyright features

### PR DESCRIPTION
**Pull request by sandrokeil**
@pmjones I've updated the docs for the latest Bookdown features of the **develop** branch. This also address [issue #16](https://github.com/bookdown/Bookdown.Bookdown/issues/16). We should bring a new shiny release of Bookdown. I think these are killer features. ;-) What do you think?

### CODE REVIEW

**Comment by sandrokeil** [comment]
@pmjones Is there a date for the next release?

**Comment by pmjones** [comment]
I agree. In fact I think we're at a point where we can call it a 1.x release. :-)  What I'll do is branch 0.x to 1.x and release from there, 1.0.0-beta1. Future PRs should go against the 1.x branch.

If you've no objection I can do that today/tomorrow. Thoughts?

**Comment by pmjones** [comment]
All right, here is what's going on:
- I have renamed "develop" to "0.x"
- I have renamed "master" to "1.x" and merged over all the develop/0.x changes
- I will release 1.0.0-beta1 from the 1.x branch
- I will then update Bookdown.Project to require ~1.0, and release it as needed
- I expect to delete the develop and master branches in favor of the new 0.x and 1.x branches

(The branch renaming is in line with the existing Aura and Atlas naming.)

**Comment by sandrokeil** [comment]
@pmjones Alright. :+1:

**Comment by pmjones** [comment]
Good deal. Writing up the changes now!

**Comment by pmjones** [comment]
@sandrokeil Done, done, and done. Website updated too!

**Comment by sandrokeil** [comment]
Yeah, it looks pretty good. :tada: Awesome!

**Pull request merged**
